title: Sistemas Ciberfísicos
description: Notas y documentación
theme: just-the-docs

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

url: "https://haiavila.github.io"
baseurl: "/sistemasCiberfisicos"   # respeta mayúsculas/minúsculas
permalink: pretty

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template